### ISSUE TITLE
changeHubState will not change

### ISSUE THREAD

**Issue by xdenneboom** [appspark-nl/rituals-api-php#1]
Hi, this is awesome work you've done! I've been able to connect to my wireless diffuser and get its values. Now I'm running in to not being able to changeHubState. I get back a 200, but the diffuser won't start diffusing. 

What I'm struggling with, is, I'm not a php developer, so Guzzle is also pretty new for me. How is the URL being constructed in the following part? I'm trying to call it in Postman to better understand. 

`    private function changeHubState(Hub $hub,$state)
    {
        $body = ['hub' => $hub->hash,'json' => ['attr' => ['fanc' => $state == 1 ? "1" : "0"]]];
        $this->client->request('POST','/api/hub/update/attr',[
            'form_params' => $body
        ]);`

**Comment by appspark-nl** [comment]
Hey!

The URL is constructed by using the baseURL at the top of the file, and appending '/api/hub/update/attr'. The Rituals API sadly always gives a 200, even it if doesn't do a thing. The diffuser is charged/powered?

**Comment by xdenneboom** [comment]
Yeah, I eventually figured it out with trial and error, yesterday late. Thanks!
