### ISSUE TITLE
Noob in php and project with ifttt

### ISSUE THREAD

**Issue by rektart** [appspark-nl/rituals-api-php#2]
Hi, thanx with your amazing job!
I am a noob with php but I would like to run my rituals genie for half an hour when I come home. And I thought with your work and ifttt it could work. i have already been able to send php requests with ifttt to my thermostat so i think it must be feasible. What do you think? could you help me to realize this project?

**Comment by appspark-nl** [comment]
Are you still looking for help?

**Comment by rektart** [comment]
Yes I am :)

**Comment by appspark-nl** [comment]
Did you get the package to turn on your diffuser without IFTTT?

**Comment by rektart** [comment]
Nope I didn’t..
