### ISSUE TITLE
update/attr not working anymore

### ISSUE THREAD

**Issue by xdenneboom** [appspark-nl/rituals-api-php#3]
Hi, I've been using the diffuser with IFTTT for a while. A few months a go it stopped working. I believe they have changed their backend. I have a postman collection with API calls based on your work here. 

How did you figure out the calls the first time? I'd like to understand what I need to change in my calls in order to figure out the new call.

**Comment by appspark-nl** [comment]
Sorry for the late response, I gotta put on those notifications...

I figured it out using an old Android phone, and installing a proxy server on a PC to intercept all traffic coming from that Android phone. I used Charles Proxy.
